### ISSUE TITLE
Incorrect network drawing for example with multiple plots of droplet.

### ISSUE THREAD

**Issue by dealmeidavf** [dpploy/cortix#186]
https://github.com/dpploy/cortix/blob/dc1b401bba1a6e9211b30703a413006a517c3cb5/cortix/src/cortix_main.py#L116

This function is not drawing the right graph of the [run_droplet_multi_plot.py](cortix/examples/fluidflow/run_droplet_multi_plot.py). Maybe the network created is incorrect too. See pic:

![network](https://user-images.githubusercontent.com/378189/62020623-bfef0e00-b191-11e9-8b62-acf8f4f28339.png)

It should be one DataPlot per Droplet and only connected to a single Droplet. The example runs correctly with MPI but does not run correctly with multiprocessing (issue is open).

**Comment by tazzaoui** [comment]
This is because the same port name "visualization" is being used for all droplets. The module drawing utility checks for port equality by checking the string name of the ports. Therefore, when it encounters the port name "visualization" in all droplets, it treats them as one port and therefore creates a diagram like the one you see. 

If you change `visualization = Port('visualization')` to `visualization = Port('visualization-{}'.format(i))` then you get the following diagram with the correct behavior: 

![network](https://user-images.githubusercontent.com/15951668/62063589-21969300-b1f9-11e9-9613-0ee7e13813eb.png)

**Comment by dealmeidavf** [comment]
This solves the drawing problem but the port name can't be changed for simulation. It is a reserved internal name for the Droplet module. This name `'visualization-{}'.format(i)` does not exist for a Droplet port.

**Comment by dealmeidavf** [comment]
https://github.com/dpploy/cortix/blob/ea1aeb289da899e97f2f44cd70326c7aa4921613/cortix/examples/fluidflow/run_droplet.py#L100

Actually this works. How is that possible if the port in `Droplet` is called `visualization`?

**Comment by dealmeidavf** [comment]
There was a but in `get_port()`. It is fixed in my branch but not the master. I will push this to master now.

**Comment by tazzaoui** [comment]
Fixed in: fc77548
