### ISSUE TITLE
Why the time argument addition?

### ISSUE THREAD

**Issue by dealmeidavf** [dpploy/cortix#265]
Why the time argument addition?

https://github.com/dpploy/cortix/blob/8a81432cc310f4fcd2bbbb4519d00d36e5851b75/cortix/examples/bwr/bwr.py#L546

**Comment by arotker45** [comment]
Shutdown reactivity insertion is based on the absolute time of the simulation, but the f_vec function only iterates over a single time step from 0 to 60 seconds. So you need to add the current simulation time to the time within the f_vec in order to get the absolute time at the current point within f_vec so you can pass that to the reactivity calculator. Without this, the reactor will never shut down.

**Comment by dealmeidavf** [comment]
https://github.com/dpploy/cortix/blob/08a9d78d6761b9002220c9995b38ee3059e3884d/cortix/examples/bwr/bwr.py#L228

Here is the proper fix.
