### ISSUE TITLE
Build a wrapper for configuration

### ISSUE THREAD

**Issue by tazzaoui** [dpploy/cortix#64]
It would be helpful to have a wrapper around the configuration system that enables us to configure cortix with python. The idea: ```python -> xml -> cortix```

**Comment by dealmeidavf** [comment]
Is this part of the GUI development?

**Comment by dealmeidavf** [comment]
Great. This will be an independent development but it will be the infrastructure for the python GUI so that the GUI focus on the user interface experience. Also CortixConfig can be used in the jpynotebooks as you said and any other python script one wants to write to configure Cortix outside the GUI or jpynotebooks. We need to find a home for CortixConfig.

**Comment by tazzaoui** [comment]
Resolved in cortix2.0
